[package]
name = "PandaCrawler"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
lazy_static = "1.4"
serde = "1.0"
serde_derive = "1.0"

[[bin]]
name = "image_data"
path = "image_data.rs"